### PR TITLE
[fix] switching from khash to dictionary of run queues

### LINKED ISSUE #222: redis-server enters an unresponsive state while running inference workflow
Considering we run RedisAI via
```
docker run -p 6379:6379 redisai/redisai:edge
```
And we do the following steps:
## 0.1 )getting the dataset

```
wget https://performance-cto-group-public.s3.amazonaws.com/benchmarks/redisai/aibench/models/tensorflow/creditcardfraud.pb  
 wget https://performance-cto-group-public.s3.amazonaws.com/benchmarks/redisai/aibench/gz/aibench_generate_data-creditcard-fraud.dat.gz
cat aibench_generate_data-creditcard-fraud.dat.gz | gunzip > aibench_generate_data-creditcard-fraud.dat
```

## 0.2 )loading the model to redis-server 
```
redis-cli -x AI.MODELSET financialNet \
            TF CPU INPUTS transaction reference \
            OUTPUTS output < creditcardfraud.pb
```

## 0.3 )loading the reference data
```
$ docker run -it -v ~/aibench_generate_data-creditcard-fraud.dat:/tmp/aibench_generate_data-creditcard-fraud.dat --network host  filipecosta90/aibench:edge aibench_load_data -reporting-period 1000ms -workers 8 -pipeline 100 -file /tmp/aibench_generate_data-creditcard-fraud.dat
-------------------------
 aibench - Docker Image  
-------------------------
Checking if request binary aibench_load_data exists
time (ns),total commands,instantaneous commands/s,overall commands/s
1568805100512833500,323972,323811.94,323811.94
1568805101518874600,569614,244167.01,283879.40
1568805102518941700,569614,0.00,189454.39
1568805103512859100,569614,0.00,142385.00
1568805104512886900,569614,0.00,113910.30
1568805105478875900,569614,0.00,94926.69
1568805106478826000,569614,0.00,81367.41
1568805107478880000,569614,0.00,71196.65
1568805108478848500,569614,0.00,63286.65
Took:    9.146 sec

...done.
```

## 1 ) running the inference ( UNRESPONSIVE )
```
$ docker run -it -v ~/aibench_generate_data-creditcard-fraud.dat:/tmp/aibench_generate_data-creditcard-fraud.dat --network host  filipecosta90/aibench:edge aibench_run_inference_redisai  -print-interval 0 -reporting-period 1000ms -workers 8 -burn-in 10 -max-queries 0 -file /tmp/aibench_generate_data-creditcard-fraud.dat -model financialNet
-------------------------
 aibench - Docker Image  
-------------------------
Checking if request binary aibench_run_inference_redisai exists
time (ns),total inferences,instantaneous inferences/s,overall inferences/s
burn-in complete after 10 queries with 8 workers
1568805167613297900,2064,2039.44,2039.44
1568805168613285800,4824,2760.03,2397.57
1568805169613363200,7444,2619.80,2471.36
1568805170617747400,8183,735.77,2037.35
1568805171613418000,8183,0.00,1632.63
1568805172613637100,8183,0.00,1361.02
1568805173617737400,8183,0.00,1166.25
1568805174613739800,8183,0.00,1021.28
1568805175616599100,8183,0.00,907.67
1568805176615028000,8183,0.00,817.17
1568805177613696500,8183,0.00,743.07
```

### PR DESCRIPTION
**Pull request by filipecosta90**
fixes #222 ( after the code changes and building a new docker image we're not able to enter into the deadlock state of before )

[fix] change from khash to dictionary of queues
[fix] run_queue_info->run_queue_mutex mutex was not initialized.
[add] using condition var to remove active wait on RedisAI_Run_ThreadMain
[del] remove the global lock since we only change the queues on the main thread

### CODE REVIEW

File: src/model.c [hunk 1]
```diff
@@ -236,6 +236,17 @@ RAI_Model *RAI_ModelCreate(RAI_Backend backend, RAI_Device device, int64_t devic
     RAI_SetError(err, RAI_EUNSUPPORTEDBACKEND, "Unsupported backend.\n");
     return NULL;
   }
+  if (device == RAI_DEVICE_CPU){
```
Comment (lantiga) [inline src/model.c]: This should be refactored: `devicestr` already provided to the command in `redisai.c` and parsed.
At this point, since we're dealing with strings as device/queue identifiers, the string should be passed directly to this function, which in turns delegates backends to accept or reject the string as a valid device.

This way the device can be made dynamic and backend-dependent (we can have MOVIDIUS:0 in ONNXRuntime).

I can do it in a follow-up PR right after this is merged.

File: src/redisai.c [hunk 2]
```diff
@@ -11,8 +11,9 @@
 
 #include "rmutil/alloc.h"
 #include "util/arr_rm_alloc.h"
+#include "util/dict.h"
+#include "util/dict.c"
```
Comment (lantiga) [inline src/redisai.c]: Why are we including `dict.c`?

File: src/redisai.c [hunk 3]
```diff
@@ -1006,25 +992,22 @@ int RedisAI_ModelRun_RedisCommand(RedisModuleCtx *ctx, RedisModuleString **argv,
...
   rinfo->client = RedisModule_BlockClient(ctx, RedisAI_Run_Reply, NULL, RedisAI_FreeData, 0);
   // RedisModule_SetDisconnectCallback(rinfo->client, RedisAI_Disconnected);
 
-  pthread_mutex_lock(&run_queue_info.run_queue_mutex);
-  queuePush(run_queue_info.run_queue, rinfo);
-  pthread_mutex_unlock(&run_queue_info.run_queue_mutex);
+  pthread_mutex_lock(&run_queue_info->run_queue_mutex);
+  queuePush(run_queue_info->run_queue, rinfo);
+  pthread_cond_signal(&run_queue_info->queue_condition_var);
+  pthread_mutex_unlock(&run_queue_info->run_queue_mutex);
```
Comment (lantiga) [inline src/redisai.c]: 👍

File: src/backends/torch.c [hunk 4]
```diff
@@ -137,6 +137,17 @@ RAI_Script *RAI_ScriptCreateTorch(RAI_Device device, int64_t deviceid, const cha
   ret->device = device;
   ret->deviceid = deviceid;
   ret->refCount = 1;
+  if (device == RAI_DEVICE_CPU){
```
Comment (lantiga) [inline src/backends/torch.c]: See my more general comment below.

File: src/redisai.c (hunk 2 above)
Comment (filipecosta90) [reply src/redisai.c]: sorry. setted it just to experiment on dict.c and then I forgot to properly adjust cmakefile. Done

File: src/model.c (hunk 1 above)
Comment (filipecosta90) [reply src/model.c]: @lantiga done. please revise the changes on all backends for model_create and on torch for script_create

File: src/backends/torch.c (hunk 4 above)
Comment (filipecosta90) [reply src/backends/torch.c]: @lantiga done. please revise the changes on all backends for model_create and on torch for script_create

File: src/model.c [hunk 5]
```diff
@@ -206,7 +207,7 @@ int RAI_ModelInit(RedisModuleCtx* ctx) {
   return RedisAI_ModelType != NULL;
 }
 
-RAI_Model *RAI_ModelCreate(RAI_Backend backend, RAI_Device device, int64_t deviceid,
+RAI_Model *RAI_ModelCreate(RAI_Backend backend, RAI_Device device, int64_t deviceid, const char* devicestr,
```
Comment (lantiga) [inline src/model.c]: I personally think we should defer parsing the `devicestr` into `RAI_Device` and `deviceid` until we hit the backend. So, remove them from `RAI_ModelCreate` and `model_create`.
Each backend will be responsible for parsing the backend and stating that it's valid.

Comment (filipecosta90) [reply src/model.c]: @lantiga please revise the latest commit. the backends are now the ones responsible for parsing the devicestr.

File: src/CMakeLists.txt [hunk 6]
```diff
@@ -15,20 +16,23 @@ ADD_LIBRARY(redisai_obj OBJECT
 IF(BUILD_TF)
     ADD_LIBRARY(redisai_tensorflow_obj OBJECT
             backends/tensorflow.c
+            backends.c
```
Comment (lantiga) [inline src/CMakeLists.txt]: I think we shouldn't add this file to the individual backends. Let's keep it only on the redisai.so side.
Let's just have `parseDeviceStr` in a `backends/util.h` file.

File: src/backends.h [hunk 7]
```diff
@@ -31,8 +31,8 @@ typedef struct RAI_LoadedBackends {
 RAI_LoadedBackends RAI_backends;
 char* RAI_BackendsPath;
 
+int parseDeviceStr(const char* devicestr, RAI_Device* device, int64_t* deviceid);
```
Comment (lantiga) [inline src/backends.h]: Let's remove this from here, see above.

Comment (filipecosta90) [reply src/backends.h]: @lantiga please see new commit.

**Comment by filipecosta90** [comment]
@rafie is the error related with this specific PR, or the WIP on circleCI? Asking this just to check if we need to double-check code on onnx changes of this PR.

**Comment by lantiga** [comment]
@filipecosta90 here are the fixes on top of this branch: https://github.com/RedisAI/RedisAI/tree/functional-runqueue-dict-onnx-fix
Feel free to merge them into this PR.

**Comment by filipecosta90** [comment]
@luca merged your changes. 
Can we go forward to master?
