### PR TITLE
 invalid memory accesses fixes and improvements

### LINKED ISSUE #340: ensure safe RAI_FreeRunInfo
```
redis-server *:6379(je_malloc_usable_size+0x6d)[0x563ae1f45add]

Backtrace:
redis-server *:6379(logStackTrace+0x32)[0x563ae1ed7572]
redis-server *:6379(sigsegvHandler+0x9e)[0x563ae1ed7c4e]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12730)[0x7fb582177730]
redis-server *:6379(je_malloc_usable_size+0x6d)[0x563ae1f45add]
redis-server *:6379(zfree+0xe)[0x563ae1e9a82e]
/root/project/bin/linux-x64-debug-cov/install-cpu/redisai.so(RAI_FreeRunInfo+0x2b5)[0x7fb581f26438]
/root/project/bin/linux-x64-debug-cov/install-cpu/redisai.so(RAI_ModelRunScriptRunReply+0x565)[0x7fb581f2f1e9]
redis-server *:6379(moduleHandleBlockedClients+0xc2)[0x563ae1f05172]
redis-server *:6379(beforeSleep+0x47)[0x563ae1e90807]
redis-server *:6379(aeMain+0x1e)[0x563ae1e8d70e]
redis-server *:6379(main+0x4ca)[0x563ae1e8a57a]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb)[0x7fb581fc809b]
redis-server *:6379(_start+0x2a)[0x563ae1e8a7da]
```

### LINKED ISSUE #341: double free. accessing invalid memory due to double management of of std::shared_ptr<torch::jit::script::Module>
This one took a while to validate, but all evidences point to invalid memory access due to free on Redis, and deleting a pointer that come from new. 
Using redis compiled with std libc allocator and building RedisAI in debug mode via:

```
make -C opt build DEBUG=1 AOF=0 SLAVES=0 GEN=1
``` 
running the torch test files and attaching gdb ot redisai crashes redis. 

```
cd tests
RLTest -t tests_pytorch --env existing-env
```

backtrace ( as you can see this invalid memory access is originated by flushallCommand ):
```
(gdb) continue
Continuing.
[Thread 0x7ff90b7fe700 (LWP 26113) exited]

Thread 1 "redis-server" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ff93accc801 in __GI_abort () at abort.c:79
#2  0x00007ff93ad15897 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ff93ae42b9a "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ff93ad1c90a in malloc_printerr (str=str@entry=0x7ff93ae40d88 "free(): invalid pointer") at malloc.c:5350
#4  0x00007ff93ad23e1c in _int_free (have_lock=0, p=0x7ff900010380, av=0x7ff93b077c40 <main_arena>) at malloc.c:4157
#5  __GI___libc_free (mem=0x7ff900010390) at malloc.c:3124
#6  0x00007ff89c2df400 in std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, torch::jit::Value*>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, torch::jit::Value*> >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::~_Hashtable() ()
   from /home/filipe/redislabs/RedisAI/bin/linux-x64-debug/install-cpu/backends/redisai_torch/lib/libtorch.so
#7  0x00007ff89c2caa53 in torch::jit::Graph::~Graph() () from /home/filipe/redislabs/RedisAI/bin/linux-x64-debug/install-cpu/backends/redisai_torch/lib/libtorch.so
#8  0x00007ff89c2a8b72 in std::_Sp_counted_ptr_inplace<torch::jit::script::CompilationUnit, std::allocator<torch::jit::script::CompilationUnit>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() ()
   from /home/filipe/redislabs/RedisAI/bin/linux-x64-debug/install-cpu/backends/redisai_torch/lib/libtorch.so
#9  0x00007ff9245caf66 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x556afba69d20) at /usr/include/c++/7/bits/shared_ptr_base.h:154
#10 0x00007ff9245c59d1 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x556afbb00f90, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/shared_ptr_base.h:684
#11 0x00007ff9245be20e in std::__shared_ptr<torch::jit::script::CompilationUnit, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x556afbb00f88, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/shared_ptr_base.h:1123
#12 0x00007ff9245be22a in std::shared_ptr<torch::jit::script::CompilationUnit>::~shared_ptr (this=0x556afbb00f88, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/shared_ptr.h:93
#13 0x00007ff9245be570 in c10::StrongTypePtr::~StrongTypePtr (this=0x556afbb00f88, __in_chrg=<optimized out>) at /home/filipe/redislabs/RedisAI/deps/linux-x64-cpu/libtorch/include/ATen/core/ivalue.h:601
#14 0x00007ff9245cb03e in c10::ivalue::Object::~Object (this=0x556afbb00f70, __in_chrg=<optimized out>) at /home/filipe/redislabs/RedisAI/deps/linux-x64-cpu/libtorch/include/ATen/core/ivalue_inl.h:313
#15 0x00007ff9245cb066 in c10::ivalue::Object::~Object (this=0x556afbb00f70, __in_chrg=<optimized out>) at /home/filipe/redislabs/RedisAI/deps/linux-x64-cpu/libtorch/include/ATen/core/ivalue_inl.h:313
#16 0x00007ff9245cb112 in c10::intrusive_ptr<c10::ivalue::Object, c10::detail::intrusive_target_default_null_type<c10::ivalue::Object> >::reset_ (this=0x556afaeb1970)
    at /home/filipe/redislabs/RedisAI/deps/linux-x64-cpu/libtorch/include/c10/util/intrusive_ptr.h:199
#17 0x00007ff9245c5b62 in c10::intrusive_ptr<c10::ivalue::Object, c10::detail::intrusive_target_default_null_type<c10::ivalue::Object> >::~intrusive_ptr (this=0x556afaeb1970, __in_chrg=<optimized out>)
    at /home/filipe/redislabs/RedisAI/deps/linux-x64-cpu/libtorch/include/c10/util/intrusive_ptr.h:244
#18 0x00007ff9245c3614 in torch::jit::script::Object::~Object (this=0x556afaeb1970, __in_chrg=<optimized out>) at /home/filipe/redislabs/RedisAI/deps/linux-x64-cpu/libtorch/include/torch/csrc/jit/script/object.h:15
#19 0x00007ff9245c3630 in torch::jit::script::Module::~Module (this=0x556afaeb1970, __in_chrg=<optimized out>) at /home/filipe/redislabs/RedisAI/deps/linux-x64-cpu/libtorch/include/torch/csrc/jit/script/module.h:97
#20 0x00007ff9245d6eee in __gnu_cxx::new_allocator<torch::jit::script::Module>::destroy<torch::jit::script::Module> (this=0x556afaeb1970, __p=0x556afaeb1970) at /usr/include/c++/7/ext/new_allocator.h:140
#21 0x00007ff9245d6de9 in std::allocator_traits<std::allocator<torch::jit::script::Module> >::destroy<torch::jit::script::Module> (__a=..., __p=0x556afaeb1970) at /usr/include/c++/7/bits/alloc_traits.h:487
#22 0x00007ff9245d6b6d in std::_Sp_counted_ptr_inplace<torch::jit::script::Module, std::allocator<torch::jit::script::Module>, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x556afaeb1960) at /usr/include/c++/7/bits/shared_ptr_base.h:535
#23 0x00007ff9245caf66 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x556afaeb1960) at /usr/include/c++/7/bits/shared_ptr_base.h:154
#24 0x00007ff9245c59d1 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x556afab5da50, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/shared_ptr_base.h:684
#25 0x00007ff9245c36c6 in std::__shared_ptr<torch::jit::script::Module, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x556afab5da48, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/shared_ptr_base.h:1123
#26 0x00007ff9245c36e2 in std::shared_ptr<torch::jit::script::Module>::~shared_ptr (this=0x556afab5da48, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/shared_ptr.h:93
#27 0x00007ff9245b8342 in (anonymous namespace)::ModuleContext::~ModuleContext (this=0x556afab5da40, __in_chrg=<optimized out>) at /home/filipe/redislabs/RedisAI/src/libtorch_c/torch_c.cpp:186
#28 0x00007ff9245b835e in (anonymous namespace)::ModuleContext::~ModuleContext (this=0x556afab5da40, __in_chrg=<optimized out>) at /home/filipe/redislabs/RedisAI/src/libtorch_c/torch_c.cpp:188
#29 0x00007ff9245ba227 in torchDeallocContext (ctx=0x556afab5da40) at /home/filipe/redislabs/RedisAI/src/libtorch_c/torch_c.cpp:415
#30 0x00007ff9245a9196 in RAI_ModelFreeTorch (model=0x556afba6d080, error=0x7ffd08fb4b90) at /home/filipe/redislabs/RedisAI/src/backends/torch.c:76
#31 0x00007ff93a088dca in RAI_ModelFree (model=0x556afba6d080, err=0x7ffd08fb4b90) at /home/filipe/redislabs/RedisAI/src/model.c:315
#32 0x00007ff93a08890b in RAI_Model_DTFree (value=0x556afba6d080) at /home/filipe/redislabs/RedisAI/src/model.c:224
#33 0x0000556af869ea55 in freeModuleObject (o=0x556afba6b5e0) at object.c:341
#34 0x0000556af869eb54 in decrRefCount (o=0x556afba6b5e0) at object.c:361
#35 0x0000556af8683eba in dictObjectDestructor (privdata=0x0, val=0x556afba6b5e0) at server.c:498
#36 0x0000556af8681f87 in _dictClear (d=0x556afa1f9a40, ht=0x556afa1f9a50, callback=0x0) at dict.c:455
#37 0x0000556af8682f3d in dictEmpty (d=0x556afa1f9a40, callback=0x0) at dict.c:989
#38 0x0000556af86a331d in emptyDb (dbnum=-1, flags=0, callback=0x0) at db.c:364
#39 0x0000556af86a3586 in flushallCommand (c=0x556afbaf6de0) at db.c:449
#40 0x0000556af8688316 in call (c=0x556afbaf6de0, flags=15) at server.c:2468
#41 0x0000556af8688fcb in processCommand (c=0x556afbaf6de0) at server.c:2763
#42 0x0000556af869a087 in processInputBuffer (c=0x556afbaf6de0) at networking.c:1470
#43 0x0000556af869a1dc in processInputBufferAndReplicate (c=0x556afbaf6de0) at networking.c:1505
#44 0x0000556af869a552 in readQueryFromClient (el=0x556afa1e4d60, fd=8, privdata=0x556afbaf6de0, mask=1) at networking.c:1587
#45 0x0000556af867f2e3 in aeProcessEvents (eventLoop=0x556afa1e4d60, flags=11) at ae.c:443
#46 0x0000556af867f4fd in aeMain (eventLoop=0x556afa1e4d60) at ae.c:501
#47 0x0000556af868cfd4 in main (argc=3, argv=0x7ffd08fb5108) at server.c:4234
(gdb) 

```

### PR DESCRIPTION
**Pull request by filipecosta90**
- [fix] fixed PyTorch errors due to invalid memory accesses. fixes #341 
- [fix] ensure safe RAI_FreeRunInfo. fixes #340

### CODE REVIEW

File: src/libtorch_c/torch_c.cpp [hunk 1]
```diff
@@ -338,10 +338,13 @@ extern "C" void* torchLoadModel(const char* graph, size_t graphlen, DLDeviceType
...
-    size_t len = strlen(e.what());
+    const char* err_message = e.what(); 
+    const size_t len = strlen(err_message);
     *error = (char*)alloc(len * sizeof(char));
-    strcpy(*error, e.what());
-    delete ctx;
+    if(*error){
+       strcpy(*error, err_message);
+    }
+    // delete ctx;
```
Comment (lantiga) [inline src/libtorch_c/torch_c.cpp:347]: We should probably still find a way to deallocate `ctx`

File: src/background_workers.h [hunk 2]
```diff
@@ -1,3 +1,4 @@
+#define _GNU_SOURCE
```
Comment (lantiga) [inline src/background_workers.h:1]: Why this? I believe this should be only set `#ifdef __linux__`

File: .circleci/config.yml [hunk 3]
```diff
@@ -19,11 +19,11 @@ commands:
             BREW_NO_UPDATE=1 ./opt/system-setup.py
             # git clone git://github.com/antirez/redis.git --branch 5.0.7; (cd redis; make malloc=libc -j $(nproc); make install); redis-server --version
             ./get_deps.sh cpu
-      - save_cache:
-          paths:
-            - deps
-            - /usr/local
-          key: build-dependencies-{{ checksum "get_deps.sh" }}
+      # - save_cache:
```
[the remark this answers is not in the document]
Comment (filipecosta90) [reply .circleci/config.yml:22]: I disabled it for safe guarding. After this test passess will push a new one enabling caching again to double check

File: src/background_workers.h (hunk 2 above)
Comment (filipecosta90) [reply src/background_workers.h:1]: #define _GNU_SOURCE is needed for the resolution of the following warning:
`implicit declaration of function ‘pthread_setname_np’ [-Wimplicit-function-declaration]`
does it break mac builds?

Comment (filipecosta90) [reply src/background_workers.h:2]: changed as per our conversation on the new commit

File: src/libtorch_c/torch_c.cpp (hunk 1 above)
Comment (filipecosta90) [reply src/libtorch_c/torch_c.cpp:347]: Agree. But I would wait for some extra unit tests to make sure that the double freeing of the shared pointers is not only visible on ci

File: .circleci/config.yml (hunk 3 above)
[the remark this answers is not in the document]
Comment (filipecosta90) [reply .circleci/config.yml]: checking on this new commit if CI with caching passes the coverage test

[the remark this answers is not in the document]
Comment (filipecosta90) [reply .circleci/config.yml]:
```
Found a cache from build 2503 at build-dependencies-g56SbIkKcrU1pwadgbiX37Oa8YFgTUciKupRTnuyJQY=
Size: 472 MiB
Cached paths:
  * /root/project/deps
  * /usr/local

Downloading cache archive...
Validating cache...

Unarchiving cache...
```
@lantiga working as expected. But I disabled the fallback to non exact dependencies. On the case of the checksum not being exact it will download new ones ( so that we can change versions and not break CI )
